In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [3]:
dataset=pd.read_csv("train.csv")
dataset.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [4]:
dataset = dataset.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)
# dataset.columns
dataset.head(1)

Survived  Pclass   Sex   Age  SibSp  Parch  Fare Embarked
0         0       3  male  22.0      1      0  7.25        S

In [5]:
le = preprocessing.LabelEncoder()
# le.fit(dataset["Sex"])
dataset["Sex"] = le.fit_transform(dataset["Sex"])
dataset["Embarked"]=le.fit_transform(dataset["Embarked"])
dataset.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [17]:
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
def abc(data):
    x = dataset.drop([data], axis=1)
    y = dataset[data]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)
    model = BernoulliNB()
    model.fit(train_x, train_y)
    ypred = model.predict(test_x)
    print("------------------------------------------------------------------")
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")
print("Survived:")
print(abc("Survived"))
print("Pclass:")
print(abc("Pclass"))
print("Sex")
print(abc("Sex"))
print("Embarked")
print(abc("Embarked"))
print("SibSp")
print(abc("SibSp"))
print("Parch")
print(abc("Parch"))

Survived:
------------------------------------------------------------------
Accuracy score is 0.7865168539325843
Confusion Matrix: 
[[87 22]
 [16 53]]
None
Pclass:
------------------------------------------------------------------
Accuracy score is 0.5786516853932584
Confusion Matrix: 
[[15 10 19]
 [ 0  8 34]
 [ 6  6 80]]
None
Sex
------------------------------------------------------------------
Accuracy score is 0.797752808988764
Confusion Matrix: 
[[53 20]
 [16 89]]
None
Embarked
------------------------------------------------------------------
Accuracy score is 0.7303370786516854
Confusion Matrix: 
[[  0   0  36]
 [  0   0  12]
 [  0   0 130]]
None
SibSp
------------------------------------------------------------------
Accuracy score is 0.6910112359550562
Confusion Matrix: 
[[108  17   0   0   0   0]
 [ 28  15   0   0   0   0]
 [  3   2   0   0   0   0]
 [  1   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  0   1   0   0   0   0]]
None
Parch
----------------------------------