# 1. Create a 3x3x3 array with random values

In [2]:
import numpy as np
np.empty((3,3))

array([[6.522e-322, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 3.933e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [3]:
np.empty((3,3,3))

array([[[9.1e-322, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np

In [5]:
a1=np.diag([1,2,3,4,0])
a1

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
b=np.zeros((8,8))
b[1::2, ::2] = 1
b[::2, 1::2] = 1

for i in range(8): 
        for j in range(8): 
            b[i][j]

print(b)  

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [7]:
import numpy as np
A= np.random.random((3,3))
print("Original Array:")
print(A)
xmax, xmin = A.max(), A.min()
A = (A - xmin)/(xmax - xmin)
print("After normalization:")
print(A)

Original Array:
[[0.1657769  0.95071525 0.22296099]
 [0.03998103 0.07439648 0.79378592]
 [0.49345748 0.55580623 0.8692982 ]]
After normalization:
[[0.13812578 1.         0.20091478]
 [0.         0.03778869 0.82768921]
 [0.49792403 0.5663839  0.91060284]]


# 5. How to find common values between two arrays?

In [8]:
import pandas as pd
a=pd.array([10,20,30,40,50,60])
b=np.array([20,80,50,70,90])
print("a=",a)
print("length(a)=",len(a))
print("b=",b)
print("Lenghth (b)=",len(b))

a= <IntegerArray>
[10, 20, 30, 40, 50, 60]
Length: 6, dtype: Int64
length(a)= 6
b= [20 80 50 70 90]
Lenghth (b)= 5


In [9]:
x=[]
for i in a:
    if i in b:
        x.append(i)
#     else:
#         print("no comman element")
print("The commane element of 2 arrays is:",x)

The commane element of 2 arrays is: [20, 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [11]:
A=np.empty((5,5))
B=np.empty((5,5))
print(A)
print("------------------------------------------------")
print(B)
equal=np.allclose(A,B)
print("After checking the equality the array is equal or not:")
print(equal)


[[ 7.41098469e-323  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [-2.19923762e-310  8.89318163e-323  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]]
------------------------------------------------
[[ 1.38338381e-322  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [-6.32779263e-310  1.28457068e-322  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000 -6.38211572e-310  6.64008201e+265  1.01231768e+190
   1.81596891e-152]]
After checking the equality the array is equal or

# 8.Create random vector of size 10 and replace the maximum value by 0

In [12]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.27638127 0.68270807 0.81924725 0.02552236 0.36298156 0.55390001
 0.79746971 0.57221977 0.52923353 0.39977917]
Maximum value replaced by 0:
[0.27638127 0.68270807 0.         0.02552236 0.36298156 0.55390001
 0.79746971 0.57221977 0.52923353 0.39977917]


# 9. How to print all the values of an array?

In [13]:
import numpy as np
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix 

In [14]:
import numpy as np
x=np.array([[1,3,5,4],[7,10,8,11],[12,22,44,55],[11,14,16,3]])
# print(x.shape)
print(x)
z=x-x.mean(axis=1)
print(z)

[[ 1  3  5  4]
 [ 7 10  8 11]
 [12 22 44 55]
 [11 14 16  3]]
[[ -2.25  -6.   -28.25  -7.  ]
 [  3.75   1.   -25.25   0.  ]
 [  8.75  13.    10.75  44.  ]
 [  7.75   5.   -17.25  -8.  ]]


In [15]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(x.shape)
print(x)
z=x-x.mean(axis=1)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [1]:
import numpy as np
A = np.ones(10)
I = np.random.randint(0,len(A),20)
A += np.bincount(I, minlength=len(A))
print(A)

[5. 2. 3. 4. 1. 2. 3. 3. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [16]:
import numpy as np
A=np.random.randint(0,10,(5,5))
B=np.random.randint(0,10,(5,5))
print(A)
print(B)

C=np.diag(np.dot(A,B))
C

[[7 5 8 5 9]
 [4 7 3 2 5]
 [5 3 8 7 1]
 [7 6 1 1 6]
 [5 3 5 5 8]]
[[0 9 6 2 6]
 [8 2 8 3 5]
 [9 8 7 4 1]
 [7 2 7 0 6]
 [0 1 4 8 6]]


array([147,  83, 163,  84, 128])

# 13.How to find the most frequent value in an array?

In [17]:
A=np.array([10,3,5,10,8,5,76,10,67,89,66,90])
print(A)
print("Most frequent value is:",np.bincount(A).argmax())

[10  3  5 10  8  5 76 10 67 89 66 90]
Most frequent value is: 10


# 14.How to get the n largest values of an array

In [18]:
import numpy as np
x=np.array([10,33,78,2,92,45,20,12,44,28])
print(x)
print(max(x))

[10 33 78  2 92 45 20 12 44 28]
92


In [19]:
A=np.array([12,89,75,80,23,55,443,34,88,90])
print("Given array :")
print(A,"\n")
x = np.unique(A)
y = np.sort(x)
n = int(input("Enter the n value for print : "))
print("\nThe",n,"largest values of given array are :")
print(y[-n:])

Given array :
[ 12  89  75  80  23  55 443  34  88  90] 

Enter the n value for print : 4

The 4 largest values of given array are :
[ 88  89  90 443]


# 15.How to create a record array from a regular array?

In [21]:
import numpy as np
A=np.array([("Python",10.5,40),("Numpy",30,20)])
print(A)
Ans=np.core.records.fromarrays(A.T,
                              names='col1,col2,col3',
                              format='S10,f10,i10')
print(Ans)

[['Python' '10.5' '40']
 ['Numpy' '30' '20']]


TypeError: fromarrays() got an unexpected keyword argument 'format'

In [3]:

import numpy as np
a =np.array(["Python","LetsUpgrade"])
b=np.array([10,20])
result=np.core.records.fromarrays([a,b])
print(result[0])
print(result[1])


('Python', 10)
('LetsUpgrade', 20)
